---

- name: Install required packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ dehydrated_packages }}"
  tags:
    - dehydrated
    - installation

- name: Checkout git repository for dehydrated
  git:
    repo: https://github.com/lukas2511/dehydrated.git
    dest: "{{dehydrated_basedir}}"
    update: "{{dehydrated_updategit}}"
    version: "{{dehydrated_commit}}"
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-git
    - installation

- name: Create dehydrated directories
  file:
    state: directory
    path: "{{item}}"
  with_items:
    - "{{dehydrated_basedir}}"
    - "{{dehydrated_configdir}}"
    - "{{dehydrated_certsdir}}"
    - "{{dehydrated_certsdir}}/current"
    - "{{dehydrated_accountsdir}}"
    - "{{dehydrated_wellknown}}"
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-dirs

- name: Template dehydrated config files
  template:
    src: "{{item}}.j2"
    dest: "{{dehydrated_basedir}}/{{item}}"
    owner: root
    group: root
  with_items:
    - config
    - domains.txt
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-domains.txt

- name: Create local.sh config file
  file:
    state: touch
    path: "{{dehydrated_configdir}}/local.sh"
    mode: 0755
  changed_when: false
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-local

- name: Create account key and accept terms
  command: "{{dehydrated_basedir}}/dehydrated --register --accept-terms"
    creates: "{{dehydrated_accountsdir}}/*/account_key.pem" 
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-account

- name: Enable cronjob for dehydrated
  template:
    src: "cronjob"
    dest: "/etc/cron.weekly/dehydrated"
    owner: root
    group: root
    mode: 0755
  when: dehydrated_cronjob|bool
  run_once: "{{dehydrated_run_once}}"
  tags:
    - dehydrated
    - dehydrated-cron
